baseURL: https://patojad.com.ar/
locale: es-AR
title: PatoJAD | Pasion por la Tecnologia
defaultContentLanguage: es
enableRobotsTXT: true
summaryLength: 10

googleAnalytics: G-21JN682W8P
theme: tailwind/
pagerSize: 12

author:
    name: PatoJAD
