baseURL: https://patojad.com.ar/
languageCode: es-AR
title: PatoJAD
defaultContentLanguage: es
enableRobotsTXT: true
canonifyurls: true

googleAnalytics: UA-131446486-2
theme: tailwind/
Paginate: 8

author:
    name: PatoJAD
