baseURL: https://patojad.com.ar/
languageCode: es-AR
title: PatoJAD
defaultContentLanguage: es

canonifyurls: true

googleAnalytics: UA-131446486-2
theme: vsk-theme-patojad-hugo/
Paginate: 6

author:
    name: PatoJAD
