baseURL: https://patojad.com.ar/
languageCode: es-AR
title: PatoJAD
defaultContentLanguage: es
enableRobotsTXT: true
canonifyurls: true
summaryLength: 10

googleAnalytics: UA-131446486-2
theme: tailwind/
pagerSize: 8

author:
    name: PatoJAD
