main:
  - identifier: inicio
    name: Inicio
    url: /
    weight: 1
    params:
      newTab: false
      icon: fas fa-home
  - identifier: blog
    name: Blog
    url: /posts
    weight: 2
    params:
      newTab: false
      icon: fas fa-blog
  - identifier: proyectos
    name: Proyectos
    url: /projects
    weight: 5
    params:
      newTab: false
      icon: fas fa-project-diagram
  - identifier: marca
    name: Marca Personal
    url: https://vasak.net.ar/
    weight: 3
    params:
      newTab: true
      icon: fas fa-briefcase

footer:
  - identifier: authors
    name: Autores
    url: /authors
  - identifier: privacity
    name: Privacidad
    url: /privacity