main:
    - identifier: inicio
      name: Inicio
      url: /
      weight: 1
      params:
          newTab: false
          haveChildren: false
    - identifier: blog
      name: Blog
      url: /posts
      weight: 2
      params:
          newTab: false
          haveChildren: false
    - identifier: sobre
      name: Sobre
      weight: 3
      params:
          haveChildren: true
          submenu:
              - identifier: sobremi
                name: Sobre Mi
                url: https://joaquindecima.ml/
                weight: 1
                newTab: true
              - identifier: sobrepato
                name: Sobre PatoJAD
                url: /about
                weight: 2
                newTab: false
    - identifier: foro
      name: Foro
      url: https://community.vasak.net.ar/
      weight: 6
      params:
          newTab: true
          haveChildren: false
    - identifier: contacto
      name: Contacto
      url: /contact
      weight: 4
      params:
          newTab: false
          haveChildren: false
    - identifier: agradecimientos
      name: Agradecimientos
      url: /gratitude
      weight: 5
      params:
          newTab: false
          haveChildren: false
