main:
    - identifier: inicio
      name: Inicio
      url: /
      weight: 1
      params:
          newTab: false
          icon: fas fa-home
    - identifier: blog
      name: Blog
      url: /posts
      weight: 2
      params:
          newTab: false
          icon: fas fa-blog
    - identifier: contacto
      name: Contacto
      url: /contact
      weight: 4
      params:
          newTab: false
          icon: fas fa-comment
    - identifier: agradecimientos
      name: Agradecimientos
      url: /gratitude
      weight: 5
      params:
          newTab: false
          icon: fas fa-hand-holding-heart
