page:
    - HTML
section:
    - HTML
    - RSS # Feed por sección (ej. /post/index.xml)
taxonomy:
    - HTML
    - RSS
term:
    - HTML
    - RSS # Feed por categoría/tag (ej. /categories/linux/index.xml)
home:
    - JSON
    - HTML
    - RSS
