baseURL = "https://patojad.com.ar/"
languageCode = "es-AR"
title = "PatoJAD"
defaultContentLanguage = "es"

canonifyurls = true

googleAnalytics="UA-131446486-2"
theme="vsk-theme-patojad-hugo/"
Paginate=6

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputs]
  page = ["HTML"] # A player
  section = ["HTML"] # All players
  home = ["json","HTML","RSS"] # Everything

[permalinks]
  posts = "/post/:year/:month/:slug/"
  page = "/:slug/"

[author]
    name = "PatoJAD"

[markup]
    [goldmark]
        [renderer]
            unsafe = true
    [tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4

[params]
    featuredImageField = "image"
    rssFullContent = true
    favicon = 'https://joaquindecima.ml/android-chrome-512x512.png'

    [footer]
        since = 2023
        customText = 'Creado con ❤ por <a href="https://vasak.net.ar" target="_blank">Vasak Group</a>'

    [dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

    [sidebar]
        emoji = "🐧"
        subtitle = "Arquitecto de Software en Banco del Sol."
        [avatar]
            enabled = true
            local = true
            src = "img/profile.jpeg"

    [article]
        math = true
        toc = true
        readingTime = true

    [comments]
        enabled = true

    [opengraph]
        [twitter]
            # Your Twitter username
            site = "PatoJADOficial"

            # Available values: summary, summary_large_image
            card = "summary_large_image"
    [defaultImage]
        enabled = true
        local = true
        src = "img/profile.jpeg"

    [colorScheme]
        # Display toggle
        toggle = true

        # Available values: auto, light, dark
        default = "auto"

    [imageProcessing]
        [cover]
            enabled = true
        [content]
            enabled = true
