baseURL = "https://patojad.gitlab.io/blog/"
languageCode = "es-ES"
title = "PatoJAD"
defaultContentLanguage = "es"

googleAnalytics="UA-131446486-2"
theme="PatoJAD/"
Paginate=6
disqusShortname = "https-patojad-gitlab-io-blog"

[taxonomies]
   tag = "tags"
   category = "categories"
