baseURL = "https://patojad.gitlab.io/"
languageCode = "es-ES"
title = "PatoJAD"
defaultContentLanguage = "es"

googleAnalytics="UA-131446486-2"
theme="PatoJAD/"
Paginate=6

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

#[outputs]
#  page = ["json","HTML"] # A player
#  section = ["json","HTML","RSS"] # All players
#  home = ["json","HTML","RSS"] # Everything
