baseURL = "https://patojad.com.ar/"
languageCode = "es-ES"
title = "PatoJAD"
defaultContentLanguage = "es"

canonifyurls = true

googleAnalytics="UA-131446486-2"
theme="PatoJAD2/"
Paginate=6

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputs]
  page = ["HTML"] # A player
  section = ["HTML"] # All players
  home = ["json","HTML","RSS"] # Everything

[permalinks]
  Aplicaciones = "/aplicaciones/:year/:month/:title"
  Estilo = "/estilo/:year/:month/:title"
  Juegos = "/juegos/:year/:month/:title"
  Lacomunidadopina = "/comunidad/:year/:month/:title"
  Linux = "/linux/:year/:month/:title"
  Noticias = "/noticias/:year/:month/:title"
  Programacion = "/programacion/:year/:month/:title"
  Redesyseguridad = "/redesyseguridad/:year/:month/:title"

[author]
    name = "PatoJAD"
