# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "PatoJAD"
license = "GPLv3"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.en.html"
description = ""
homepage = "https://patojad.tk/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "PatoJAD"
  homepage = "https://patojad.tk/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
